# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tawsif
email: tawsif1130@gmail.com
description: I write about software, research engineering and DevOps of AI and Machine learning here. I have a separate research blog and website to document research-specific stuff.
twitter_username: sleeping4cat
github_username: sleepingcat4
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "tawsif"
  avatar : "/assets/images/shocked-cat.jpg"
  bio    : "I write about software, research engineering and DevOps here."
  links:
    - label: "Website"
      icon: "fa-regular fa-browser"
      url: "https://sleeping4cat.github.io/sleepingcat/"
    - label: "Twitter"
      icon: "fa-brands fa-square-x-twitter"
      url: "https://x.com/sleeping4cat"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/sleepingcat4"

footer:
  links:
    - label: "Twitter"
      icon: "fa-brands fa-square-x-twitter"
      url: "https://x.com/sleeping4cat"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/sleepingcat4"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
